name: Bark Test Ubuntu Headless 

on:
  push:
    branches:
      - act-trigger
  workflow_dispatch:


jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Check Python version
        run: python --version
        
      - name: Install the system packages
        run: |
          sudo apt-get update &&
          sudo apt-get install -y wget git calibre ffmpeg nodejs espeak espeak-ng rustc cargo libmecab-dev mecab mecab-ipadic-utf8 curl &&
          sudo apt-get clean &&
          sudo rm -rf /var/lib/apt/lists/*
      - name: Install the python requirements
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install -r requirements.txt

      - name: pip Install unict
        run: pip install unidic

      - name: Download the unict dictionary
        run: python -m unidic download

      - name: Help command python app.py
        run: python app.py --help

      - name: Create test files
        run: |
          mkdir workflow-testing
          echo "This is test sentence 1 ." > workflow-testing/test1.txt
          echo "This is test sentence 2 ." > workflow-testing/test2.txt
          echo "This is test sentence 3 ." > workflow-testing/test3.txt
          echo "This is test sentence 4 ." > workflow-testing/test4.txt
          echo "This is test sentence 5 ." > workflow-testing/test5.txt

      - name: English Bark headless single test python app.py
        run: python app.py --headless --language eng --ebook "workflow-testing/test1.txt" --tts_engine bark

      - name: English Bark headless batch test python app.py
        run: python app.py --headless --language eng --ebooks_dir "workflow-testing" --tts_engine bark

      - name: English Bark Custom-Voice headless single test python app.py
        run: python app.py --headless --language eng --ebook "workflow-testing/test1.txt" --tts_engine bark --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: English Bark Custom-Voice headless batch test python app.py
        run: python app.py --headless --language eng --ebooks_dir "workflow-testing" --tts_engine bark --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Unusual Bark headless single test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebook "workflow-testing/test1.txt" --tts_engine bark

      - name: Unusual Bark headless batch test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebooks_dir "workflow-testing" --tts_engine bark

      - name: Unusual Bark Custom-Voice headless single test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebook "workflow-testing/test1.txt" --tts_engine bark --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"

      - name: Unusual Bark  Custom-Voice headless batch test python app.py
        run: python app.py --headless --language urd-script_devanagari --ebooks_dir "workflow-testing" --tts_engine bark --voice "voices/eng/elder/male/DavidAttenborough_24000.wav"
