name: README translation

on:
  push:
    branches:
      - v25
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Translate README into multiple languages
      - name: Adding README - Swedish
        uses: dephraiim/translate-readme@main
        with:
          LANG: sv
          
      - name: Adding README - Persian
        uses: dephraiim/translate-readme@main
        with:
          LANG: fa